# -*- coding: utf-8 -*-
"""
This is the script for downloading .csv files from the specified URL daily.

The majority of the code here was generated by ChatGPT, with tweaks made where needed to update info.
"""

import requests
from pathlib import Path
from datetime import date

URL = "https://covid.ourworldindata.org/data/latest/owid-covid-latest.csv"

output_dir = Path("data/raw")
output_dir.mkdir(parents=True, exist_ok=True)

filename = output_dir / f"data_{date.today()}.csv"

response = requests.get(URL, timeout=30)
response.raise_for_status()

filename.write_bytes(response.content)

print(f"Downloaded {filename}")