# -*- coding: utf-8 -*-
"""
This is the script for loading the processed data into PostgreSQL.

The majority of the code here was generated by ChatGPT, with tweaks made where needed to update info.
"""

import pandas as pd
from sqlalchemy import create_engine
import os
from dotenv import load_dotenv

load_dotenv()

#(Probably need to substitute some values into these bits)(actually, probably need to set values in .env file)
engine = create_engine(
    f"postgresql+psycopg2://{os.getenv('PG_USER')}:{os.getenv('PG_PASSWORD')}"
    f"@{os.getenv('PG_HOST')}:{os.getenv('PG_PORT')}/{os.getenv('PG_DB')}"
)

df = pd.read_csv("data/processed/clean_data.csv")

df.to_sql(
    "daily_data",
    engine,
    if_exists="append",    #This line may need to change in some way, depending on how processed is handled
    index=False
)

print("Data loaded into PostgreSQL")